swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /upload:
    post:
      operationId: module.unpack
      summary: Uploads a file.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
        - in: formData
          name: bankid
          type: string
          description: Blazegraph bank id.
      responses:
        201:
          description: Successfully created person in list
